### ISSUE TITLE
Usage with .NET Core Web API

### ISSUE THREAD

**Issue by patoncrispy** [epsagon/epsagon-dotnet#10]
I'm using the .NET Core Web API as a single function and implementing the `APIGatewayProxyFunction` abstract base class. As a result, I cannot implement `LambdaHandler`. I also cannot use `EpsagonHandler.Handle` because I do not have access to the `FunctionHandlerAsync` required to start up the API. 

Is there any other way of adding tracing support?

**Comment by ranrib** [comment]
Hi @patoncrispy - we would love to add support for that for you. Can we get in touch through email to get some more info? (ran@epsagon.com)
