### ISSUE TITLE
Handle function with return type Task

### ISSUE THREAD

**Issue by patoncrispy** [epsagon/epsagon-dotnet#11]
I have a lambda function that only returns `Task` and so I cannot implement `LambdaHandler`. Could a handler be added for functions with no return type? I'm changing my return type to return an `int` in the meantime as a hack.

**Comment by tvaintrob** [comment]
Hi @patoncrispy, thank you for taking the time to open an issue !
You can use `EpsagonHandler.Handle`, it has an overload that takes in a `Func<Task>` and returns the inner `Task` which is your use case if i'm correct, if you have any issues with it let me know
